// 檔案路徑：yuanassist/model/AgentRepository.kt
package com.example.yuanassist.model

data class AgentAttr(val element: String, val profession: String)

object AgentRepository {
    val ALL_AGENTS = arrayOf(
        "蛾使",
        "陆逊",
        "贾诩",
        "严白虎",
        "颜良",
        "张辽",
        "郭解",
        "夏侯惇",
        "许攸",
        "陈登",
        "吕蒙",
        "郭嘉",
        "华佗",
        "文丑",
        "阿蝉",
        "严颜",
        "杨修",
        "伍丹",
        "小乔",
        "张仲景",
        "关靖",
        "鸢使",
        "高览",
        "鲁肃",
        "孙权",
        "甘缇",
        "崔烈",
        "山九",
        "史子眇",
        "孙尚香",
        "周瑜",
        "荀彧",
        "张角",
        "第五天",
        "飞云",
        "张修",
        "干吉",
        "雀使",
        "周群",
        "毛玠",
        "王粲",
        "庞统",
        "眭固",
        "绣球",
        "李脱",
        "楼班",
        "杨阜",
        "许曼",
        "蔡琰",
        "程昱",
        "徐稺",
        "蜂使",
        "陆绩",
        "王异",
        "太史慈",
        "李真",
        "葛洪",
        "张飞",
        "马超",
        "张闿",
        "公孙珊",
        "甘宁",
        "孔融",
        "董奉",
        "诸葛瑾",
        "徐庶",
        "甄宓",
        "黄月英",
        "曹植",
        "满宠",
        "张郃",
        "张鲁",
        "张邈",
        "诸葛诞",
        "荀攸",
        "凌统",
        "戏学",
        "黄盖",
        "刘豹",
        "张昭",
        "安期",
        "令狐茂",
        "祢衡",
        "张绣",
        "士燮",
        "刘繇",
        "朱然",
        "蒯越",
        "董白",
        "虞翻",
        "张燕",
        "诸葛亮",
        "司马徽"
    )

    val AGENT_MAP = mapOf(
        "刘豹" to AgentAttr("水", "神纪"),
        "安期" to AgentAttr("地", "破军"),
        "张燕" to AgentAttr("火", "神纪"),
        "董奉" to AgentAttr("阳", "岐黄"),
        "贾诩" to AgentAttr("阴", "诡道"),
        "马超" to AgentAttr("地", "破军"),
        "孙尚香" to AgentAttr("火", "破军"),
        "蔡琰" to AgentAttr("水", "诡道"),
        "黄月英" to AgentAttr("阳", "龙盾"),
        "夏侯惇" to AgentAttr("地", "龙盾"),
        "荀彧" to AgentAttr("风", "神纪"),
        "周瑜" to AgentAttr("水", "神纪"),
        "徐庶" to AgentAttr("阳", "神纪"),
        "张邈" to AgentAttr("风", "神纪"),
        "张角" to AgentAttr("阴", "破军"),
        "诸葛瑾" to AgentAttr("水", "破军"),
        "甄宓" to AgentAttr("火", "神纪"),
        "张飞" to AgentAttr("风", "破军"),
        "张闿" to AgentAttr("阴", "诡道"),
        "张郃" to AgentAttr("火", "神纪"),
        "士燮" to AgentAttr("水", "诡道"),
        "孔融" to AgentAttr("水", "神纪"),
        "凌统" to AgentAttr("火", "破军"),
        "诸葛亮" to AgentAttr("阳", "神纪"),
        "张绣" to AgentAttr("阴", "破军"),
        "满宠" to AgentAttr("阴", "破军"),
        "张昭" to AgentAttr("风", "神纪"),
        "王粲" to AgentAttr("水", "神纪"),
        "孙权" to AgentAttr("火", "龙盾"),
        "令狐茂" to AgentAttr("水", "神纪"),
        "刘繇" to AgentAttr("水", "诡道"), // 保持你原本的配置
        "蒯越" to AgentAttr("火", "神纪"),
        "程昱" to AgentAttr("火", "诡道"),
        "诸葛诞" to AgentAttr("火", "神纪"),
        "曹植" to AgentAttr("风", "诡道"),
        "杨修" to AgentAttr("阳", "神纪"),
        "戏学" to AgentAttr("地", "诡道"),
        "张鲁" to AgentAttr("阴", "诡道"),
        "黄盖" to AgentAttr("阴", "诡道"),
        "陆逊" to AgentAttr("火", "破军"),
        "鲁肃" to AgentAttr("水", "诡道"),
        "张修" to AgentAttr("火", "诡道"),
        "虞翻" to AgentAttr("阴", "破军"),
        "张辽" to AgentAttr("地", "破军"),
        "华佗" to AgentAttr("阳", "岐黄"),
        "张仲景" to AgentAttr("地", "岐黄"),
        "于吉" to AgentAttr("火", "诡道"),
        "郭嘉" to AgentAttr("风", "诡道"),
        "郭解" to AgentAttr("火", "龙盾"),
        "葛洪" to AgentAttr("阴", "诡道"),
        "司马徽" to AgentAttr("阴", "诡道"),
        "太史慈" to AgentAttr("风", "破军"),
        "朱然" to AgentAttr("阳", "龙盾"),
        "庞统" to AgentAttr("阳", "神纪"),
        "董白" to AgentAttr("地", "神纪"),
        "荀攸" to AgentAttr("地", "诡道"),
        "甘宁" to AgentAttr("水", "诡道"),
        "祢衡" to AgentAttr("阳", "神纪"),
        "吕蒙" to AgentAttr("火", "破军"),
        "颜良" to AgentAttr("水", "龙盾"),
        "史子渺" to AgentAttr("风", "岐黄"),
        "陈登" to AgentAttr("风", "神纪"),
        "阿蝉" to AgentAttr("地", "破军"),
        "王异" to AgentAttr("风", "龙盾"),
        "飞云" to AgentAttr("火", "龙盾")
    )
}