package com.example.yuanassist.utils

const val BATTLE_FLOW_TEST_TASK_KEY = "TASK_BATTLE_FLOW"
const val BATTLE_FLOW_START_BATTLE_OCR_DELAY_KEY = "START_BATTLE_OCR"
const val BATTLE_FLOW_FIRST_ACTION_DELAY_OPTION = "FIRST_TURN_FIRST_ACTION_DELAY"
