package com.example.yuanassist.utils

const val DAI_BAN_GONG_WU_START_BATTLE_DELAY_OPTION = "DAI_BAN_GONG_WU_START_BATTLE_DELAY"
const val MAINLINE_624_START_BATTLE_DELAY_OPTION = "MAINLINE_624_START_BATTLE_DELAY"
